// React_Node/react_node_frontend/src/version_2/components/RegisterBook.js
import { useState, useContext } from "react"
import bookService from '../services/bookService'
import { BookContext } from '../ContainerV2'
import "bootstrap/dist/css/bootstrap.min.css";
import '../stylesheets/RegisterBook.css'

export default function RegisterBook(props) {
    let { book, setBook, bookList, setBookList } = useContext(BookContext)
    let [status, setStatus] = useState("Press submit to add/update a book.....");
    let [statusClass, setStatusClass] = useState("")
    //============================================================================================
    function validateBook()
    {
        let errors = "";

        if (book.bookId <= 0)
          errors += "bookId should be > 0, "
        if (book.bookName.length < 3)
          errors += "bookName must have atleast 3 characters, "
        if (book.bookPrice <= 0)
          errors += "bookPrice  should be > 0"

        return errors;
    }
    //===========================================================================================================
    async function handleSubmit(e) {
        e.preventDefault();

        let errorString = validateBook();
        if (errorString.length != 0)
        {
            setStatus("Cannot submit...." + errorString)
            setStatusClass("error")
            return;
        }
        else
            setStatusClass("success")

            console.log("okokok")
        let response = (await bookService.getBook(book.bookId))
  
        console.log(response)
        console.log(response.data.book);
        let foundBook = response.data.book;

        if (!foundBook) {
            await bookService.postBook(book);
            setStatus(`Book with id :  ${book.bookId}  posted successfully....`);
        }
        else {
            await bookService.updateBook(book);
            setStatus(`Updated book from { ${foundBook.bookId} , ${foundBook.bookName}, ${foundBook.bookPrice} }
                        to  { ${book.bookId} , ${book.bookName}, ${book.bookPrice} } `);
        }

        let books = (await bookService.getAllBooks()).data.books;
        setBookList(books);
        setBook({ bookId: '', bookName: '', bookPrice: '' })

    }
    //=======================================================================================================
    return (
        <div className = 'register_book'>

            <div className="form-group form-container">
                <form>

                    <div>
                        <label for='bookId'>Book Id : </label>
                        <input
                            className="form-control"
                            type='number'
                            id='bookId'
                            value={book.bookId}
                            onChange={(e) => { setBook({ ...book, bookId: e.target.value }) }}
                        />
                    </div>
                    
                    <div>
                        <label for='bookName'>Book Name : </label>
                        <input
                            className="form-control"
                            type='text'
                            id='bookName'
                            value={book.bookName}
                            onChange={(e) => { setBook({ ...book, bookName: e.target.value }) }}

                        />
                    </div>

                    <div>
                        <label for='bookPrice'>Book Price : </label>
                        <input
                            className="form-control"
                            type='number'
                            id='bookPrice'
                            value={book.bookPrice}
                            onChange={(e) => { setBook({ ...book, bookPrice: e.target.value }) }}

                        />
                    </div>

                    <div>
                        <button 
                            className="btn btn-success"
                            onClick={(e) => { handleSubmit(e) }}>Submit</button>

                    </div>
                </form>
            </div>

            <div className="display-container">
                <p className = {statusClass}><b>Status : </b> {status}</p>
                <p>
                    <b>Current Book Details : </b> 
                    {
                        (book.bookId == 0)? 
                    `Details not yet entered.....` 
                        
                        :
                    `Book Id : ${book.bookId} , 
                        Book Name : ${book.bookName}, 
                        Book Price : ${book.bookPrice} ` 
                    }
                </p>
            </div>

        </div>
    )
}

// Angular_Spring/angular_spring_frontend/src/app/components/template_driven/registerbook/registerbook.component.ts
import { Component } from '@angular/core';

import { FormsModule } from '@angular/forms';
import { BookdaoService } from '../../../services/bookdao.service';
import { Router } from '@angular/router';
import { Book } from '../../../model/Book';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-registerbook1',
  standalone: true,
  imports: [FormsModule, CommonModule],
  templateUrl: './registerbook.component.html',
  styleUrl: './registerbook.component.css'
})
export class RegisterbookComponent {
  private bookService: BookdaoService;
  myBook: Book;
  status: string;
  static bookIdx: number = 1;


  constructor(bookService: BookdaoService, private router: Router) {
    this.bookService = bookService;
    this.myBook = new Book(RegisterbookComponent.bookIdx, "Dummy", 1000);
    this.status = "Book details not yet submitted....."
  }

  goList(): void {
    this.router.navigateByUrl('/listbooks');
  }

  addBook(): void {
    let tempBook: Book = this.myBook;
    if (this.myBook.bookId <= 0 || this.myBook.bookName == "" || this.myBook.bookPrice <= 0) {
      this.status = "Book validation failed. Cannot add book......";
    }
    else {
      this.bookService.create(this.myBook).subscribe(
        {
          next: (res) => {

            console.log(res)
            let b: Book = res;
            console.log(b, b.bookName)
            this.status = "Added " + b.bookId + ",  " + b.bookName + ", " + b.bookPrice + " successfully....";


          },
          error: (err) => {
            console.log(err);
            this.status = "Book " + tempBook + " not posted , Cause  : " + err.error.message;
            ;
            RegisterbookComponent.bookIdx = tempBook.bookId
            this.myBook.bookId = tempBook.bookId;


          },
          complete: () => {

          }
        }
      );
    }
    RegisterbookComponent.bookIdx++;
    this.myBook = new Book(RegisterbookComponent.bookIdx, 'Dummy', 1000);
  }
}

<form (ngSubmit)="addBook()" #bookForm=ngForm>


  <!-- =========================================================================================== -->
  <div class='form-group'>

    <label for="bookId">
      Book Id:
    </label>

    <input type="number" [(ngModel)]="myBook.bookId" name="id" required id="bookId" #id="ngModel" disabled
      class='form-control' />


    <div [hidden]="id.valid||id.pristine" class='alert alert-danger'>
      BookId cannot be empty.
    </div>
  </div>

  <!-- ======================================================================================== -->
  <div class='form-group'>
    <label for="bookName">
      Book Name :
    </label>

    <input type="text" [(ngModel)]="myBook.bookName" name="bookName" minlength="3" pattern="^[a-zA-Z_ ]+$" required
      id="bookName" #bookName="ngModel" class='form-control' />


    <!-- "|| bookPrice.pristine" -->
    <div [hidden]="bookName.valid" class='alert alert-danger'>
      Book Name is invalid
      <div>
        @if(bookName.errors?.['required'])
        {
        Book name is required
        }
        @if(bookName.errors?.['minlength'])
        {
        Book name should have minLength = {{bookName.errors?.['minlength'] | json}}
        }
        @if(bookName.errors?.['pattern'])
        {
        Pattern not met....{{bookName.errors?.['pattern'] | json}}

        }
      </div>

    </div>
  </div>
  <!-- ========================================================================================================= -->

  <div class='form-group'>
    <label for="bookPrice">
      Book Price :
    </label>
    <input type="number" [(ngModel)]="myBook.bookPrice" name="bookPrice" required id="bookPrice" #bookPrice="ngModel"
      min="100" class='form-control' />


    
    <!-- "|| bookPrice.pristine" -->
    <div [hidden]="bookPrice.valid" class='alert alert-danger'>
      Book Price cannot be empty.

      @if (bookPrice.errors?.['min'])
      {
      Price is below minPrice {{bookPrice.errors?.['min'] | json}}
      }
    </div>
  </div>
  <!-- ========================================================================================================= -->
  <div class='form-group'>
    <input type='submit' class='btn btn-success' [disabled]="!bookForm.form.valid" value='Add Book'>
    <div [hidden]="bookForm.valid" class='alert alert-danger'>
      Book is invalid (Cannot Submit)

    </div>
  </div>
</form>

<hr>
<!--==================================================================================================-->


<!--==================================================================================================-->

<h3>Current Book Details</h3>
@if (myBook.bookId != 0 || myBook.bookName != '' || myBook.bookPrice != 0)
{
<div>
  Book Id : {{myBook.bookId}},
  Book Name : {{myBook.bookName}},
  Book Price: {{myBook.bookPrice}}
</div>

}
@else {
<p>Book details not entered yet....</p>
}
<button (click)='goList()'>See List</button>
<hr>

<!--==================================================================================================-->
<h3>Status</h3>

<p>{{status}}</p>

<hr>
<!--==================================================================================================-->
